
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[412] =
    {   0,
        0,    0,   65,   63,    2,    1,    1,   51,   63,   12,
       57,   50,   63,   45,   46,   55,   54,   42,   53,   49,
       56,    5,    5,   43,   38,   58,   44,   59,   62,   39,
       47,   48,   60,    4,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   40,   61,   41,   52,    1,   37,
        0,    6,    0,    0,    0,    0,   12,   23,   32,   24,
        0,    0,    0,    0,    0,   21,   29,   19,   30,   20,
       31,    0,    8,    0,    0,   22,    8,    5,    0,    0,
        8,    0,    0,    0,    5,    0,   15,   28,   34,   36,

       35,   27,   25,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,    4,   12,   12,   12,   12,   12,   12,
       12,   12,    4,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   26,   33,    6,    0,    0,    0,   10,   10,    0,
        0,    0,   16,    8,    8,    0,    0,    0,    0,    3,
        8,    0,    5,    0,    5,    0,    8,    0,    5,    5,
       18,   17,   13,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,

       12,   12,   12,   12,   12,    4,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    0,    0,    0,
        0,    0,    0,    0,    8,    3,    8,    0,    0,    8,
        5,    5,    0,    8,    8,    0,    0,    0,    5,    5,
        0,    0,   14,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,    0,    9,    4,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,

       12,   12,   12,   12,   12,    7,   12,   12,   12,    0,
        0,    0,    0,    8,    0,    8,    0,    0,    0,    0,
        8,   12,   12,   12,   12,   12,   12,   12,   12,    4,
       12,   12,   12,   12,   12,   12,    0,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,    4,   12,   12,    0,    8,    8,    0,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,    0,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   11,
       12,   12,   12,   12,   12,    0,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    0,   12,   12,

       12,   12,   12,   12,    0,   12,   12,    4,   12,   12,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   31,   33,   34,   33,
        7,    7,    7,    7,    7,   35,    7,    7,    7,   36,
        7,    7,    7,    7,    7,    7,    7,   37,    7,    7,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,    7,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    1,
        6,    6,    6,    6,    7,    8,    3,    1,    1,    1,
        1,    8,    6,    6,    6,    6,    6,    6,    3,    3,
        3,    3,    7,    3,    3,    3,    8,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[422] =
    {   0,
        0,    0,  952,  953,  953,  953,  948,  923,   66,    0,
      922,   64,   55,  953,  953,  921,   65,  953,   62,   79,
       90,  101,  150,  923,  953,   54,  919,   55,  953,  953,
      953,  953,  918,    0,   53,   53,   86,   60,   72,  101,
      888,  105,  887,  886,  118,  884,  132,  893,  138,  131,
      879,   72,   60,  887,  953,   57,  953,  953,  953,  953,
      187,  931,  195,  199,  222,  226,    0,  953,  953,  953,
      926,  230,  235,  256,  253,  953,  953,  953,  953,  953,
      953,  918,  296,  921,    0,  953,  301,  318,  283,  111,
      953,  338,  916,  344,   79,  353,  953,  905,  953,  953,

      953,  113,  953,  871,  870,  873,  881,  866,   90,  883,
      882,  869,  875,  860,  861,  858,  101,  866,  863,  861,
      857,  854,    0,  857,   95,  858,  866,  850,  846,  854,
      855,  860,  861,  846,  112,  860,  222,  860,  846,  152,
      844,  849,  844,  127,  228,  851,  838,  159,  845,  834,
      847,  953,  953,  953,  368,  372,  378,  953,  953,  403,
      883,  409,  953,    0,  953,  418,  423,  879,  164,    0,
      447,  433,  953,  440,  211,  382,  454,    0,  455,  953,
      953,  953,  864,  829,  842,  835,  844,  839,  838,  839,
      824,  822,  162,  837,  814,  797,  788,  781,  789,  768,

      780,  779,  765,  216,  759,  772,  769,  755,  764,  797,
      759,  756,  757,  750,  739,  221,  746,  737,  724,  707,
      715,  707,  703,  711,  713,  698,  713,  685,  688,  688,
      689,  674,  687,  689,  677,  679,  675,  495,  501,  505,
      530,  536,  553,  509,  558,  953,    0,  563,  596,  601,
      269,  953,  290,  606,  953,  636,  271,  167,  554,  953,
      646,  628,  953,  659,  655,  666,  652,  642,  631,  629,
      633,  620,  627,  620,  617,  624,  617,  592,  604,  591,
      603,  585,  589,  578,  580,    0,  578,  594,  585,  592,
      586,  581,  580,  571,  562,  551,  562,  542,  551,  554,

      539,  550,  544,  529,  528,    0,  526,  526,  526,  655,
      667,  677,  681,  689,  704,  719,  728,  378,  379,  734,
      752,  524,  505,  522,  509,  509,  514,  499,  508,  500,
      494,  486,  491,  490,  490,  472,  471,  464,  449,  448,
      461,  459,  459,  453,  439,  437,  442,  441,  424,  434,
      424,  419,  427,  420,  757,  768,  953,  761,  419,  403,
      395,  390,  390,  388,  367,  380,  381,  366,  353,  338,
      322,  334,  319,  332,  330,  321,  312,  232,  303,  786,
      290,  299,  290,  294,  295,  286,  290,  276,  273,  274,
      272,  271,  249,  252,  237,  240,  248,  244,  240,  222,

      207,  195,  188,  199,  183,  146,  142,  953,  129,  118,
      953,  826,  832,  840,  848,  856,  860,  866,  140,  870,
      873
    } ;

static const flex_int16_t yy_def[422] =
    {   0,
      411,    1,  411,  411,  411,  411,  411,  411,  412,  413,
      411,  411,  414,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  411,  411,  411,  411,  411,  411,
      412,  411,  412,  412,  412,  411,  413,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  415,  416,  411,  411,   22,   23,  411,
      411,  411,  417,  411,   23,  411,  411,  411,  411,  411,

      411,  411,  411,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  411,  411,  411,  418,  412,  412,  411,  411,  411,
      411,  411,  411,   83,  411,  411,  411,  415,  415,  416,
      411,  411,  411,  411,  411,  411,  411,  419,  420,  411,
      411,  411,  411,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,

      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  418,  418,  418,
      418,  418,  411,  411,  411,  411,  171,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  421,  419,  420,  411,
      411,  259,  411,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  411,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,

      413,  413,  413,  413,  413,  413,  413,  413,  413,  418,
      418,  418,  418,  411,  411,  411,  411,  421,  421,  411,
      411,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  411,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  418,  411,  411,  411,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  411,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  418,
      413,  413,  413,  413,  413,  411,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  411,  413,  413,

      413,  413,  413,  413,  411,  413,  413,  411,  413,  413,
        0,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411
    } ;

static const flex_int16_t yy_nxt[1025] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   24,   25,   26,   27,   28,   29,   30,
       10,   10,   10,   10,   10,   10,   10,   31,    4,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   10,
       42,   10,   43,   44,   45,   46,   47,   10,   48,   49,
       50,   51,   52,   53,   10,   54,   10,   55,   56,   57,
       58,   62,   69,   72,   72,   72,   73,   79,   77,   98,
       99,  101,  102,  152,   63,   63,   63,   64,   80,   81,
       70,   78,   74,   75,   74,   82,  104,   83,   83,   83,

       83,   83,   84,   65,   66,   65,  113,   85,  106,  149,
      150,  107,  105,  180,  147,  114,   86,   87,  108,   88,
       88,   88,   88,   89,  115,  153,  116,  148,  109,  175,
      175,  180,   90,   91,   92,  110,  117,   93,  111,  182,
      183,  112,   94,  118,   90,  257,   91,   92,   91,  189,
      190,  119,  123,  120,  205,  206,  121,  198,  124,  125,
      128,  199,  215,  123,  129,   93,   87,  216,   95,   95,
       95,   95,   95,  130,  133,  410,  169,  228,  134,  131,
      144,  246,   91,   92,  138,  229,  123,  139,  123,  145,
      135,   96,  154,  136,  223,   91,   92,   91,  140,  141,

      154,  142,  261,  143,  154,   63,   63,   63,   64,  233,
      224,  234,  409,  156,  156,  156,  157,  156,  156,  156,
      157,  270,  271,  261,   65,   66,   65,  154,  408,  251,
      251,   61,   65,   66,   65,   61,   65,   66,   65,  159,
       63,   63,   63,   64,  159,  252,  123,  123,  160,  160,
      160,  160,  253,  161,  161,  161,  161,  407,  161,   65,
       66,   65,  161,  252,   61,  158,  218,  123,  279,   61,
      230,  280,  406,   61,  162,  162,  162,  162,  392,  219,
       61,  291,  220,  292,   61,  123,   61,  251,  251,  231,
      405,  161,  393,  123,  123,  404,  161,  403,  123,  402,

      161,   89,   89,   89,   89,   89,  261,  161,  251,  251,
      253,  161,  319,  161,  164,  164,  164,  164,  164,  171,
      171,  171,  171,  171,  174,  401,  400,  261,  165,  166,
      123,  253,  123,   91,  172,  123,  399,  167,  398,  397,
      396,  165,  166,  165,  395,  123,   91,  172,   91,  411,
      123,  176,  173,  176,  411,  394,  177,  177,  177,  177,
      177,  411,   88,   88,   88,   88,   89,  391,  390,  239,
      173,   95,   95,   95,   95,   95,  389,  154,  388,  387,
      123,  123,  411,  154,  123,   94,  240,  240,  240,  241,
      156,  156,  156,  157,   96,  386,  156,  156,  156,  157,

      177,  177,  177,  177,  177,  242,  243,  242,  385,   65,
       66,   65,  158,  261,  411,   65,   66,   65,  158,  319,
      319,  161,  161,  161,  161,  384,  383,  161,  161,  161,
      161,  244,  123,  244,  261,  411,  245,  245,  245,  245,
      245,  164,  164,  164,  164,  164,  249,  123,  249,  123,
      123,  250,  250,  250,  250,  250,  382,  123,   89,   89,
       89,   89,   89,  381,  167,  247,  247,  247,  247,  247,
      379,  258,  254,  254,  254,  254,  254,  378,  123,   91,
      172,  174,  377,  123,  376,  123,  255,  123,  248,  260,
      261,  123,   91,  172,   91,  256,  262,  375,  123,  255,

      310,  255,  239,  123,  374,  373,  310,  260,  372,  371,
      310,  261,  370,  240,  240,  240,  241,  369,  123,  240,
      240,  240,  241,  311,  311,  311,  312,  245,  245,  245,
      245,  245,  242,  243,  242,  310,  123,  368,  242,  243,
      242,  310,  242,  243,  242,  367,  123,  366,  311,  311,
      311,  312,  365,  364,  240,  240,  240,  241,  313,  363,
      123,  362,  313,  361,  360,  123,  359,  242,  243,  242,
      258,  123,  123,  242,  243,  242,  314,  314,  314,  314,
      314,  247,  247,  247,  247,  247,  354,  353,  260,  261,
      165,  313,  352,  351,  350,  262,  313,  123,  349,  315,

      313,  348,  123,  165,  248,  165,  260,  313,  347,  346,
      261,  313,  345,  313,  250,  250,  250,  250,  250,  316,
      316,  316,  316,  316,  254,  254,  254,  254,  254,  344,
      343,  342,  341,   91,  340,  339,  338,  123,  255,  337,
      336,  335,  317,  334,  411,  333,   91,  256,   91,  332,
      331,  255,  123,  255,  254,  254,  254,  254,  254,  320,
      355,  320,  411,  411,  321,  321,  321,  321,  321,  330,
      306,  329,  310,  240,  240,  240,  241,  256,  328,  327,
      411,  326,  310,  325,  411,  311,  311,  311,  312,  123,
      123,  123,  242,  243,  242,  311,  311,  311,  312,  240,

      240,  240,  241,  123,  242,  243,  242,  314,  314,  314,
      314,  314,  324,  323,  242,  243,  242,  322,  242,  243,
      242,  165,  314,  314,  314,  314,  314,  309,  123,  308,
      315,  307,  123,  123,  165,  306,  165,  316,  316,  316,
      316,  316,  305,  304,  123,  315,  316,  316,  316,  316,
      316,   91,  321,  321,  321,  321,  321,  303,  302,  301,
      317,  300,  380,  299,   91,  298,   91,  297,  296,  317,
      356,  356,  356,  356,  356,  240,  240,  240,  241,  356,
      356,  356,  356,  356,  357,  295,  356,  356,  356,  356,
      356,  380,  294,  358,  242,  243,  242,  357,  293,  357,

      357,  290,  358,  289,  240,  240,  240,  241,  288,  358,
      287,  286,  285,  357,  284,  357,  283,  123,  282,  281,
      123,  278,  277,  242,  243,  242,   61,  276,   61,   61,
       61,   61,   61,   61,   67,  275,  274,   67,   67,   67,
       71,  123,   71,  123,   71,   71,   71,   71,  168,  168,
      168,  168,  168,  168,  168,  168,  170,  273,  170,  170,
      170,  170,  170,  170,  179,  179,  238,  238,  238,  238,
      238,  238,  238,  238,  259,  259,  259,  259,  318,  272,
      318,  269,  123,  268,  123,  123,  267,  266,  265,  264,
      263,  169,  158,  237,  236,  235,  123,  232,  227,  226,

      225,  222,  221,  217,  214,  213,  212,  211,  210,  123,
      209,  208,  207,  204,  203,  123,  202,  201,  200,  197,
      196,  195,  194,  193,  192,  191,  188,  187,  186,  185,
      184,  181,  178,  169,  163,  158,  155,  151,  146,  137,
      132,  127,  126,  122,  103,  100,   97,   76,   68,   60,
       59,  411,    3,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411
    } ;

static const flex_int16_t yy_chk[1025] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,   12,   13,   13,   13,   13,   19,   17,   26,
       26,   28,   28,   56,    9,    9,    9,    9,   19,   19,
       12,   17,   13,   13,   13,   20,   35,   20,   20,   20,

       20,   20,   21,    9,    9,    9,   38,   21,   36,   53,
       53,   36,   35,   95,   52,   38,   21,   22,   36,   22,
       22,   22,   22,   22,   39,   56,   39,   52,   37,   90,
       90,   95,   22,   22,   22,   37,   39,   22,   37,  102,
      102,   37,   22,   40,   22,  419,   22,   22,   22,  109,
      109,   40,   42,   40,  125,  125,   40,  117,   42,   42,
       45,  117,  135,  410,   45,   22,   23,  135,   23,   23,
       23,   23,   23,   45,   47,  409,  169,  144,   47,   45,
       50,  169,   23,   23,   49,  144,   50,   49,  407,   50,
       47,   23,   61,   47,  140,   23,   23,   23,   49,   49,

       63,   49,  258,   49,   64,   61,   61,   61,   61,  148,
      140,  148,  406,   63,   63,   63,   63,   64,   64,   64,
       64,  193,  193,  258,   61,   61,   61,   65,  405,  175,
      175,   66,   63,   63,   63,   66,   64,   64,   64,   72,
       65,   65,   65,   65,   73,  175,  404,  403,   72,   72,
       72,   72,  175,   73,   73,   73,   73,  402,   75,   65,
       65,   65,   75,  175,   66,   74,  137,  401,  204,   66,
      145,  204,  400,   66,   74,   74,   74,   74,  378,  137,
       66,  216,  137,  216,   66,  399,   66,  251,  251,  145,
      398,   75,  378,  145,  397,  396,   75,  395,  394,  393,

       75,   89,   89,   89,   89,   89,  257,   75,  253,  253,
      251,   75,  257,   75,   83,   83,   83,   83,   83,   87,
       87,   87,   87,   87,   89,  392,  391,  257,   83,   83,
      390,  253,  389,   87,   87,  388,  387,   83,  386,  385,
      384,   83,   83,   83,  383,  382,   87,   87,   87,   88,
      381,   92,   88,   92,   88,  379,   92,   92,   92,   92,
       92,   88,   94,   94,   94,   94,   94,  377,  376,  155,
       88,   96,   96,   96,   96,   96,  375,  156,  374,  373,
      372,  371,   88,  157,  370,   94,  155,  155,  155,  155,
      156,  156,  156,  156,   96,  369,  157,  157,  157,  157,

      176,  176,  176,  176,  176,  155,  155,  155,  368,  156,
      156,  156,  160,  318,  319,  157,  157,  157,  162,  318,
      319,  160,  160,  160,  160,  367,  366,  162,  162,  162,
      162,  166,  365,  166,  318,  319,  166,  166,  166,  166,
      166,  167,  167,  167,  167,  167,  172,  364,  172,  363,
      362,  172,  172,  172,  172,  172,  361,  360,  174,  174,
      174,  174,  174,  359,  167,  171,  171,  171,  171,  171,
      354,  179,  177,  177,  177,  177,  177,  353,  352,  171,
      171,  174,  351,  350,  349,  348,  177,  347,  171,  179,
      179,  346,  171,  171,  171,  177,  179,  345,  344,  177,

      238,  177,  239,  343,  342,  341,  239,  179,  340,  339,
      240,  179,  338,  238,  238,  238,  238,  337,  336,  239,
      239,  239,  239,  240,  240,  240,  240,  244,  244,  244,
      244,  244,  238,  238,  238,  241,  335,  334,  239,  239,
      239,  242,  240,  240,  240,  333,  332,  331,  241,  241,
      241,  241,  330,  329,  242,  242,  242,  242,  243,  328,
      327,  326,  243,  325,  324,  323,  322,  241,  241,  241,
      259,  309,  308,  242,  242,  242,  245,  245,  245,  245,
      245,  248,  248,  248,  248,  248,  307,  305,  259,  259,
      245,  243,  304,  303,  302,  259,  243,  301,  300,  245,

      243,  299,  298,  245,  248,  245,  259,  243,  297,  296,
      259,  243,  295,  243,  249,  249,  249,  249,  249,  250,
      250,  250,  250,  250,  254,  254,  254,  254,  254,  294,
      293,  292,  291,  250,  290,  289,  288,  287,  254,  285,
      284,  283,  250,  282,  262,  281,  250,  254,  250,  280,
      279,  254,  278,  254,  256,  256,  256,  256,  256,  261,
      310,  261,  262,  262,  261,  261,  261,  261,  261,  277,
      276,  275,  311,  310,  310,  310,  310,  256,  274,  273,
      262,  272,  312,  271,  262,  311,  311,  311,  311,  270,
      269,  268,  310,  310,  310,  312,  312,  312,  312,  313,

      313,  313,  313,  267,  311,  311,  311,  314,  314,  314,
      314,  314,  266,  265,  312,  312,  312,  264,  313,  313,
      313,  314,  315,  315,  315,  315,  315,  237,  236,  235,
      314,  234,  233,  232,  314,  231,  314,  316,  316,  316,
      316,  316,  230,  229,  228,  315,  317,  317,  317,  317,
      317,  316,  320,  320,  320,  320,  320,  227,  226,  225,
      316,  224,  355,  223,  316,  222,  316,  221,  220,  317,
      321,  321,  321,  321,  321,  355,  355,  355,  355,  358,
      358,  358,  358,  358,  321,  219,  356,  356,  356,  356,
      356,  380,  218,  321,  355,  355,  355,  321,  217,  321,

      356,  215,  358,  214,  380,  380,  380,  380,  213,  356,
      212,  211,  210,  356,  209,  356,  208,  207,  206,  205,
      203,  202,  201,  380,  380,  380,  412,  200,  412,  412,
      412,  412,  412,  412,  413,  199,  198,  413,  413,  413,
      414,  197,  414,  196,  414,  414,  414,  414,  415,  415,
      415,  415,  415,  415,  415,  415,  416,  195,  416,  416,
      416,  416,  416,  416,  417,  417,  418,  418,  418,  418,
      418,  418,  418,  418,  420,  420,  420,  420,  421,  194,
      421,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  168,  161,  151,  150,  149,  147,  146,  143,  142,

      141,  139,  138,  136,  134,  133,  132,  131,  130,  129,
      128,  127,  126,  124,  122,  121,  120,  119,  118,  116,
      115,  114,  113,  112,  111,  110,  108,  107,  106,  105,
      104,   98,   93,   84,   82,   71,   62,   54,   51,   48,
       46,   44,   43,   41,   33,   27,   24,   16,   11,    8,
        7,    3,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
        #include<iostream>
        #include<string>
        #include<utility>
        #include <fstream>
        #include <vector>
        #include <algorithm>
        #include <unordered_map>
        using namespace std;
        #include "ast.h"
        #include "parser.hpp"
        void count(void);
        int line = 1;

        unordered_map<string,yytokentype>m(
                {
                        {"abstract",ABSTRACT},
                        {"continue",CONTINUE},
                        {"for",FOR},
                        {"new",NEW},
                        // {"switch",SWITCH},
                        {"assert",ASSERT},
                        {"default",DEFAULT},
                        {"if",IF},
                        {"package",PACKAGE},
                        {"synchronized",SYNCHRONIZED},
                        {"boolean",BOOLEAN},
                        // {"do",DO},
                        // {"goto",GOTO},
                        {"private",PRIVATE},
                        {"this",THIS},
                        {"break",BREAK},
                        {"double",DOUBLE},
                        {"implements",IMPLEMENTS},
                        // {"protected",PROTECTED},
                        {"throw",THROW},
                        {"byte",BYTE},
                        {"else",ELSE},
                        // {"import",IMPORT},
                        {"public",PUBLIC},
                        {"throws",THROWS},
                        // {"case",CASE},
                        {"enum",ENUM},
                        {"instanceof",INSTANCEOF},
                        {"return",RETURN},
                        {"transient",TRANSIENT},
                        // {"catch",CATCH},
                        {"extends",EXTENDS},
                        {"int",INT},
                        {"short",SHORT},
                        // {"try",TRY},
                        {"char",CHAR},
                        {"final",FINAL},
                        {"interface",INTERFACE},
                        {"static",STATIC},
                        {"void",VOID},
                        {"class",CLASS},
                        {"finally",FINALLY},
                        {"long",LONG},
                        {"strictfp",STRICTFP},
                        {"volatile",VOLATILE},
                        // {"const",CONST},
                        {"float",FLOAT},
                        {"native",NATIVE},
                        {"super",SUPER},
                        {"while",WHILE},
                        // {"_",UNDERSCORE},
                        {"exports",EXPORTS},
                        {"opens",OPENS},
                        {"requires",REQUIRES},
                        {"uses",USES},
                        {"module",MODULE},
                        {"permits",PERMITS},
                        {"sealed",SEALED},
                        {"var",VAR},
                        {"non-sealed",NON_SEALED},
                        {"provides",PROVIDES},
                        {"to",TO},
                        {"with",WITH},
                        {"open",OPEN},
                        {"record",RECORD},
                        {"transitive",TRANSITIVE},
                        {"yield",YIELD}
                }
        )
        ;
#line 895 "lex.yy.c"
#line 896 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 123 "lexer.l"


#line 1116 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 412 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 953 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 125 "lexer.l"
{count();}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 126 "lexer.l"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 127 "lexer.l"
{}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 128 "lexer.l"
{yylval.str = strdup(yytext); count();return m[string(yytext)];}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 129 "lexer.l"
{yylval.str = strdup(yytext); count(); return integerLiteral;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 130 "lexer.l"
{yylval.str = strdup(yytext); count(); return stringLiteral;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 131 "lexer.l"
{yylval.str = strdup(yytext); count(); return booleanLiteral;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 132 "lexer.l"
{yylval.str = strdup(yytext); count(); return FloatingPointLiteral;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 133 "lexer.l"
{yylval.str = strdup(yytext); count(); return nullLiteral;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 134 "lexer.l"
{yylval.str = strdup(yytext); count(); return characterLiteral;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 135 "lexer.l"
{yylval.str = strdup(yytext); count(); return textBlock;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 136 "lexer.l"
{yylval.str = strdup(yytext); count(); return Identifier;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 137 "lexer.l"
{yylval.str = strdup(yytext); count(); return(UNSIGNED_RIGHT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 138 "lexer.l"
{yylval.str = strdup(yytext); count(); return(UNSIGNED_RIGHT_ASSIGN); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 139 "lexer.l"
{yylval.str = strdup(yytext); count(); return(METHOD_REFERENCE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 140 "lexer.l"
{yylval.str = strdup(yytext); count(); return(ELLIPSIS); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 141 "lexer.l"
{yylval.str = strdup(yytext); count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 142 "lexer.l"
{yylval.str = strdup(yytext); count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 143 "lexer.l"
{yylval.str = strdup(yytext); count(); return(ADD_ASSIGN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 144 "lexer.l"
{yylval.str = strdup(yytext); count(); return(SUB_ASSIGN); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 145 "lexer.l"
{yylval.str = strdup(yytext); count(); return(MUL_ASSIGN); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 146 "lexer.l"
{yylval.str = strdup(yytext); count(); return(DIV_ASSIGN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 147 "lexer.l"
{yylval.str = strdup(yytext); count(); return(MOD_ASSIGN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 148 "lexer.l"
{yylval.str = strdup(yytext); count(); return(AND_ASSIGN); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 149 "lexer.l"
{yylval.str = strdup(yytext); count(); return(XOR_ASSIGN); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 150 "lexer.l"
{yylval.str = strdup(yytext); count(); return(OR_ASSIGN); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 151 "lexer.l"
{yylval.str = strdup(yytext); count(); return(RIGHT_OP); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 152 "lexer.l"
{yylval.str = strdup(yytext); count(); return(LEFT_OP); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 153 "lexer.l"
{yylval.str = strdup(yytext); count(); return(INC_OP); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 154 "lexer.l"
{yylval.str = strdup(yytext); count(); return(DEC_OP); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 155 "lexer.l"
{yylval.str = strdup(yytext); count(); return(PTR_OP); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 156 "lexer.l"
{yylval.str = strdup(yytext); count(); return(AND_OP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 157 "lexer.l"
{yylval.str = strdup(yytext); count(); return(OR_OP); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 158 "lexer.l"
{yylval.str = strdup(yytext); count(); return(LE_OP); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 159 "lexer.l"
{yylval.str = strdup(yytext); count(); return(GE_OP); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 160 "lexer.l"
{yylval.str = strdup(yytext); count(); return(EQ_OP); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 161 "lexer.l"
{yylval.str = strdup(yytext); count(); return(NE_OP); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 162 "lexer.l"
{yylval.str = strdup(yytext); count(); return(';'); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 163 "lexer.l"
{yylval.str = strdup(yytext); count(); return('@'); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 164 "lexer.l"
{yylval.str = strdup(yytext); count(); return('{'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 165 "lexer.l"
{yylval.str = strdup(yytext); count(); return('}'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 166 "lexer.l"
{yylval.str = strdup(yytext); count(); return(','); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 167 "lexer.l"
{yylval.str = strdup(yytext); count(); return(':'); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 168 "lexer.l"
{yylval.str = strdup(yytext); count(); return('='); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 169 "lexer.l"
{yylval.str = strdup(yytext); count(); return('('); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 170 "lexer.l"
{yylval.str = strdup(yytext); count(); return(')'); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 171 "lexer.l"
{yylval.str = strdup(yytext); count(); return('['); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 172 "lexer.l"
{yylval.str = strdup(yytext); count(); return(']'); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 173 "lexer.l"
{yylval.str = strdup(yytext); count(); return('.'); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 174 "lexer.l"
{yylval.str = strdup(yytext); count(); return('&'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 175 "lexer.l"
{yylval.str = strdup(yytext); count(); return('!'); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 176 "lexer.l"
{yylval.str = strdup(yytext); count(); return('~'); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 177 "lexer.l"
{yylval.str = strdup(yytext); count(); return('-'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 178 "lexer.l"
{yylval.str = strdup(yytext); count(); return('+'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 179 "lexer.l"
{yylval.str = strdup(yytext); count(); return('*'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 180 "lexer.l"
{yylval.str = strdup(yytext); count(); return('/'); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 181 "lexer.l"
{yylval.str = strdup(yytext); count(); return('%'); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 182 "lexer.l"
{yylval.str = strdup(yytext); count(); return('<'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 183 "lexer.l"
{yylval.str = strdup(yytext); count(); return('>'); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 184 "lexer.l"
{yylval.str = strdup(yytext); count(); return('^'); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 185 "lexer.l"
{yylval.str = strdup(yytext); count(); return('|'); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 186 "lexer.l"
{yylval.str = strdup(yytext); count(); return('?'); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 187 "lexer.l"
{yylval.str =  "<EOF>"; return eof;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 188 "lexer.l"
{
        cout<<"illegal character on line "<<line<<" :"<<yytext<<endl;
        return -1;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 193 "lexer.l"
ECHO;
	YY_BREAK
#line 1504 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 412 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 412 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 411);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 193 "lexer.l"


int yywrap()
{
      return(1);
}

void count(void)
{
      for (int i = 0; yytext[i] != '\0'; i++) 
        if (yytext[i] == '\n') line ++;
      return;  
}


