
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[439] =
    {   0,
        0,    0,   66,   64,    2,    1,    1,   52,   64,   12,
       58,   51,   64,   46,   47,   56,   55,   43,   54,   50,
       57,    5,    5,   44,   39,   59,   45,   60,   63,   40,
       48,   49,   61,    4,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   41,   62,   42,   53,    1,   38,
        0,    0,    6,    0,    0,    0,    0,   12,   24,   33,
       25,    0,    0,    0,    0,    0,    0,    0,    0,   22,
       30,   20,   31,   21,   32,    0,    8,    0,    0,   23,
        8,    5,    0,    0,    8,    0,    0,    0,    5,    0,

       16,   29,   35,   37,   36,   28,   26,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    4,   12,   12,
       12,   12,   12,   12,   12,   12,    4,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   27,   34,    6,    0,    0,
        0,    0,    0,    0,   13,   13,   13,   10,    0,    0,
       13,   13,   13,    0,   10,   13,   13,   13,    0,   17,
        8,    8,    0,    0,    0,    0,    3,    8,    0,    5,
        0,    5,    0,    8,    0,    5,    5,   19,   18,   14,

       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,    4,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   13,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    8,
        3,    8,    0,    0,    8,    5,    5,    0,    8,    8,
        0,    0,    0,    5,    5,    0,    0,   15,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,

       12,   12,   12,   12,   12,   12,   12,   12,   12,    0,
        9,    4,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        7,   12,   12,   12,    0,    0,    0,    0,    0,    0,
        8,    0,    8,    0,    0,    0,    0,    8,   12,   12,
       12,   12,   12,   12,   12,   12,    4,   12,   12,   12,
       12,   12,   12,    0,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,    4,   12,
       12,    0,    8,    8,    0,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,    0,   12,   12,   12,   12,

       12,   12,   12,   12,   12,   12,   11,   12,   12,   12,
       12,   12,    0,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,    0,   12,   12,   12,   12,   12,
       12,    0,   12,   12,    4,   12,   12,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   31,   33,   34,   33,
        7,    7,    7,    7,    7,   35,    7,    7,    7,   36,
        7,    7,    7,    7,    7,    7,    7,   37,    7,    7,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,    7,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    2,    2,    1,    3,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    1,
        6,    6,    6,    6,    7,    8,    4,    1,    1,    1,
        1,    8,    6,    6,    6,    6,    6,    6,    4,    4,
        4,    4,    7,    4,    4,    4,    8,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[457] =
    {   0,
        0,    0, 1161, 1162, 1162, 1162, 1157, 1132,   69,    0,
     1131,   65,   74, 1162, 1162, 1130,   71, 1162,   83,   83,
      102,  113,  162, 1132, 1162,   53, 1128,   54, 1162, 1162,
     1162, 1162, 1127,    0,   57,   60,   75,   92,   87,   98,
     1097,   89, 1096, 1095,  115, 1093,  127, 1102,  126,  113,
     1088,  110,   36, 1096, 1162,   95, 1162, 1162, 1162, 1162,
      194,  120, 1140,  199,  221,  225,  245,    0, 1162, 1162,
     1162,  263,  265,  164,  267,  275,  288,  308,  277, 1162,
     1162, 1162, 1162, 1162, 1162, 1128,  320, 1131,    0, 1162,
      325,  342,  361,  174, 1162,  371, 1126,  377,  103,  389,

     1162, 1115, 1162, 1162, 1162,  179, 1162, 1081, 1080, 1083,
     1091, 1076,  151, 1093, 1092, 1079, 1085, 1070, 1071, 1068,
      165, 1076, 1073, 1071, 1067, 1064,    0, 1067,  175, 1068,
     1076, 1060, 1056, 1064, 1065, 1070, 1071, 1056,  124, 1070,
      241, 1070, 1056,  158, 1053, 1031, 1009,  140,  210,  970,
      944,  199,  939,  928,  941, 1162, 1162, 1162,  981,  402,
      414,  424,  311,  449,  253,  316,  346,  319,   73,  360,
      220,  422,  446,  330,  348,  455,  457,  475,  480, 1162,
        0, 1162,  484,  489,  973,  342,    0,  513,  499, 1162,
      506,  521,  530,  545,    0,  537, 1162, 1162, 1162,  958,

      923,  936,  929,  938,  933,  932,  933,  917,  911,  315,
      927,  925,  920,  911,  908,  916,  901,  917,  909,  895,
      349,  889,  902,  896,  882,  886,  919,  881,  878,  879,
      872,  862,  227,  871,  866,  859,  858,  866,  859,  856,
      865,  868,  846,  861,  845,  842,  841,  848,  834,  846,
      848,  837,  833,  829, 1162,  563,  586,  590,  594,  598,
      617,  629,  660,  664,  653,  489,  513,  534,  620,  696,
     1162,    0,  668,  701,  712,  395, 1162,  482,  728, 1162,
      743,  415,  246,  736, 1162,  761,  751, 1162,  819,  818,
      829,  810,  790,  776,  766,  775,  755,  754,  747,  748,

      755,  748,  738,  751,  738,  752,  735,  739,  728,  730,
        0,  728,  736,  722,  726,  720,  708,  706,  697,  704,
      693,  699,  682,  690,  695,  680,  692,  686,  666,  668,
        0,  666,  679,  679,  790,  794,  799,  803,  825,  829,
      833,  838,  851,  866,  616,  618,  881,  890,  670,  650,
      666,  652,  653,  658,  635,  649,  641,  639,  616,  619,
      623,  617,  615,  610,  606,  592,  586,  601,  599,  599,
      585,  563,  566,  553,  553,  536,  545,  530,  526,  530,
      529,  908,  920, 1162,  935,  532,  521,  513,  510,  510,
      502,  492,  510,  500,  500,  499,  492,  470,  467,  430,

      439,  435,  433,  417,  419,  395,  953,  386,  392,  383,
      382,  371,  360,  359,  341,  329,  331,  323,  314,  314,
      314,  296,  281,  288,  284,  278,  262,  244,  238,  214,
      214,  212,  187,  118, 1162,   80,   75, 1162,  993,  998,
     1006, 1014, 1022, 1030, 1038, 1046, 1054, 1062, 1066, 1072,
     1080, 1088, 1096,   91, 1100, 1103
    } ;

static const flex_int16_t yy_def[457] =
    {   0,
      438,    1,  438,  438,  438,  438,  438,  438,  439,  440,
      438,  438,  441,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  438,  438,  438,  438,  438,  438,
      439,  442,  438,  439,  439,  439,  443,  440,  438,  438,
      438,  444,  445,  446,  444,  444,  444,  444,  444,  438,
      438,  438,  438,  438,  438,  438,  438,  447,  448,  438,
      438,   22,   23,  438,  438,  438,  449,  438,   23,  438,

      438,  438,  438,  438,  438,  438,  438,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  438,  438,  438,  438,  450,
      439,  439,  443,  451,  452,  445,  453,  452,  445,  445,
      445,  453,  453,  452,  452,  452,  452,  452,  452,  438,
       87,  438,  438,  438,  447,  447,  448,  438,  438,  438,
      438,  438,  438,  438,  454,  455,  438,  438,  438,  438,

      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  438,  450,  450,  450,  450,  450,
      438,  451,  451,  451,  438,  453,  453,  453,  438,  438,
      438,  188,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  456,  454,  455,  438,  438,  284,  438,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,

      440,  440,  440,  440,  440,  440,  440,  440,  440,  438,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  450,  450,  450,  450,  451,  451,
      438,  438,  438,  438,  456,  456,  438,  438,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  438,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  450,  438,  438,  438,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  438,  440,  440,  440,  440,

      440,  440,  440,  440,  440,  440,  450,  440,  440,  440,
      440,  440,  438,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  438,  440,  440,  440,  440,  440,
      440,  438,  440,  440,  438,  440,  440,    0,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438
    } ;

static const flex_int16_t yy_nxt[1234] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   24,   25,   26,   27,   28,   29,   30,
       10,   10,   10,   10,   10,   10,   10,   31,    4,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   10,
       42,   10,   43,   44,   45,   46,   47,   10,   48,   49,
       50,   51,   52,   53,   10,   54,   10,   55,   56,   57,
       58,   62,   62,   70,   63,  438,   73,   74,  102,  103,
      105,  106,  171,   75,   81,  153,  154,   64,   64,   64,
       65,   71,   76,   76,   76,   77,  282,   82,   83,   86,

      108,   87,   87,   87,   87,   87,   66,   67,   66,   84,
       85,   78,   79,   78,   88,  110,  109,  113,  111,   89,
      127,  156,   62,   62,  114,  112,  437,  115,   90,   91,
      116,   92,   92,   92,   92,   93,  127,  197,  117,  119,
      122,  120,  128,  129,   94,   95,   96,  118,  123,   97,
      124,  121,  151,  125,   98,  197,   94,  132,   95,   96,
       95,  133,  148,  157,  127,  152,  166,  173,  127,  137,
      134,  149,  142,  138,  232,  143,  135,   97,   91,  233,
       99,   99,   99,   99,   99,  139,  144,  145,  140,  146,
      245,  147,  192,  192,   95,   96,   62,   62,  246,  158,

      240,   62,   62,  100,  158,  199,  200,   95,   96,   95,
      206,  207,   64,   64,   64,   65,  241,  161,  161,  161,
      162,  215,  438,   62,   62,  216,  158,   62,   62,  171,
      158,   66,   67,   66,  222,  223,   66,   67,   66,  161,
      161,  161,  162,   64,   64,   64,   65,   62,   62,  250,
      164,  251,  247,  436,   61,   73,  266,  435,   66,   67,
       66,  127,   66,   67,   66,  166,  167,   73,  170,  166,
      167,  248,  168,  127,  171,  127,  174,  166,  167,  166,
      167,  286,  177,   61,  175,  235,  179,  316,   61,  317,
      166,  167,   61,  176,  176,  176,  176,  175,  236,   61,

      434,  237,  286,   61,  127,   61,  177,  177,  177,  177,
      166,  167,  433,   62,   62,  177,  438,  168,   73,  170,
      177,   73,  266,  127,  177,  171,  178,  178,  178,  178,
      432,  177,   73,  266,  127,  177,  431,  177,  181,  181,
      181,  181,  181,  188,  188,  188,  188,  188,   73,  268,
       73,  266,  182,  183,  186,  172,  430,   95,  189,  271,
      127,  184,   73,  170,  429,  182,  183,  182,  428,  171,
       95,  189,   95,  438,  295,  296,  190,  427,  438,   93,
       93,   93,   93,   93,  193,  438,  193,  127,  127,  194,
      194,  194,  194,  194,  190,   92,   92,   92,   92,   93,

      127,  304,  191,  257,  305,  426,  438,   99,   99,   99,
       99,   99,  425,  276,  276,  424,   62,   62,   98,  158,
      258,  258,  258,  259,   73,  268,   62,   62,  423,  158,
      100,  172,  161,  161,  161,  162,  278,  422,  127,  260,
      261,  260,  161,  161,  161,  162,  127,  421,   73,  268,
      286,   66,   67,   66,  158,  172,  346,   73,  266,   73,
      266,   66,   67,   66,  168,  419,  168,  262,  262,  262,
      263,  286,  418,  179,  179,  179,  179,   73,  266,  420,
      417,  416,   73,  266,  168,  415,  264,  265,  264,  168,
      414,   73,  268,  179,  179,  179,  179,  269,  172,  269,

      276,  276,  270,  270,  270,  270,  270,  181,  181,  181,
      181,  181,  274,  127,  274,   73,  268,  275,  275,  275,
      275,  275,  172,  278,   93,   93,   93,   93,   93,  127,
      184,  272,  272,  272,  272,  272,   73,  268,  127,  276,
      276,  413,  412,  172,  411,   95,  189,  191,  194,  194,
      194,  194,  194,  283,  273,  277,  410,  127,   95,  189,
       95,  127,  278,  279,  279,  279,  279,  279,  335,  127,
      127,  285,  286,  277,  409,  127,  408,  280,  287,  406,
      405,  258,  258,  258,  259,  127,  281,  257,  404,  285,
      280,  335,  280,  286,  127,  335,  403,  127,  127,  335,

      260,  261,  260,  335,  258,  258,  258,  259,  336,  336,
      336,  337,  336,  336,  336,  337,  258,  258,  258,  259,
      127,  402,  338,  260,  261,  260,  338,  260,  261,  260,
      127,  260,  261,  260,  158,  260,  261,  260,  270,  270,
      270,  270,  270,  127,  401,  400,  399,  339,  339,  339,
      340,  286,  398,  438,  397,  338,  396,  346,  164,  346,
      338,  127,  164,  127,  338,  158,  264,  265,  264,  158,
      395,  338,  286,  394,  438,  338,  127,  338,  339,  339,
      339,  340,  262,  262,  262,  263,  272,  272,  272,  272,
      272,  164,  393,  392,  391,  390,  164,  264,  265,  264,

      164,  264,  265,  264,  127,  389,  388,  164,  387,  273,
      127,  164,  386,  164,  341,  341,  341,  341,  341,  275,
      275,  275,  275,  275,  127,  127,  381,  380,  182,  379,
      343,  343,  343,  343,  343,  378,  377,  342,  127,  376,
      375,  182,  127,  182,   95,  374,  279,  279,  279,  279,
      279,  373,  283,  344,  372,  371,  370,   95,  369,   95,
      280,  279,  279,  279,  279,  279,  368,  438,  367,  281,
      285,  286,  366,  280,  347,  280,  347,  287,  365,  348,
      348,  348,  348,  348,  281,  438,  438,  127,  285,  364,
      363,  362,  286,  361,  360,  382,  359,  358,  127,  335,

      357,  331,  356,  438,  335,  355,  354,  438,  258,  258,
      258,  259,  336,  336,  336,  337,  353,  336,  336,  336,
      337,  258,  258,  258,  259,  352,  127,  260,  261,  260,
      158,  260,  261,  260,  158,  127,  260,  261,  260,  127,
      260,  261,  260,  339,  339,  339,  340,  339,  339,  339,
      340,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  127,  264,  265,  264,  182,  264,  265,  264,  343,
      343,  343,  343,  343,  342,  351,  350,  349,  182,  342,
      182,  334,  127,   95,  343,  343,  343,  343,  343,  333,
      332,  127,  344,  127,  331,  330,   95,  329,   95,  348,

      348,  348,  348,  348,  127,  328,  327,  344,  383,  383,
      383,  383,  383,  407,  326,  325,  324,  323,  322,  321,
      320,  319,  384,  318,  315,  314,  258,  258,  258,  259,
      313,  385,  312,  311,  310,  384,  309,  384,  383,  383,
      383,  383,  383,  308,  127,  260,  261,  260,  307,  306,
      127,  303,  384,  383,  383,  383,  383,  383,  407,  302,
      301,  385,  300,  299,  127,  384,  127,  384,  298,  297,
      294,  258,  258,  258,  259,  127,  385,  293,  127,  127,
      292,  291,  290,  289,  288,  186,  255,  254,  253,  252,
      260,  261,  260,   61,   61,   61,   61,   61,   61,   61,

       61,   68,  127,   68,   68,   68,   72,   72,   72,   72,
       72,   72,   72,   72,  159,  159,  249,  159,  159,  159,
      159,  159,  163,  163,  163,  163,  163,  163,  163,  163,
      165,  165,  165,  165,  165,  165,  165,  165,  169,  169,
      169,  169,  169,  169,  169,  169,  172,  172,  172,  172,
      172,  172,  172,  172,  185,  185,  185,  185,  185,  185,
      185,  185,  187,  244,  187,  187,  187,  187,  187,  187,
      196,  196,  256,  256,  256,  256,  256,  256,  256,  256,
      164,  243,  164,  164,  164,  164,  164,  164,  174,  174,
      174,  174,  174,  174,  174,  174,  267,  267,  267,  267,

      267,  267,  267,  267,  284,  284,  284,  284,  345,  242,
      345,  239,  238,  234,  231,  230,  229,  228,  227,  127,
      226,  225,  224,  221,  220,  127,  219,  218,  217,  214,
      213,  212,  211,  210,  209,  208,  205,  204,  203,  202,
      201,  198,  195,  186,  180,  160,  155,  150,  141,  136,
      131,  130,  126,  107,  104,  101,   80,   69,   60,   59,
      438,    3,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438
    } ;

static const flex_int16_t yy_chk[1234] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,    9,   12,    9,  169,   13,   13,   26,   26,
       28,   28,  169,   13,   17,   53,   53,    9,    9,    9,
        9,   12,   13,   13,   13,   13,  454,   17,   19,   20,

       35,   20,   20,   20,   20,   20,    9,    9,    9,   19,
       19,   13,   13,   13,   21,   36,   35,   37,   36,   21,
      437,   56,   62,   62,   37,   36,  436,   37,   21,   22,
       37,   22,   22,   22,   22,   22,   42,   99,   38,   39,
       40,   39,   42,   42,   22,   22,   22,   38,   40,   22,
       40,   39,   52,   40,   22,   99,   22,   45,   22,   22,
       22,   45,   50,   56,  434,   52,   74,   74,   50,   47,
       45,   50,   49,   47,  139,   49,   45,   22,   23,  139,
       23,   23,   23,   23,   23,   47,   49,   49,   47,   49,
      148,   49,   94,   94,   23,   23,   61,   61,  148,   61,

      144,   64,   64,   23,   64,  106,  106,   23,   23,   23,
      113,  113,   61,   61,   61,   61,  144,   64,   64,   64,
       64,  121,  171,   65,   65,  121,   65,   66,   66,  171,
       66,   61,   61,   61,  129,  129,   64,   64,   64,   65,
       65,   65,   65,   66,   66,   66,   66,   67,   67,  152,
       67,  152,  149,  433,   67,  165,  165,  432,   65,   65,
       65,  431,   66,   66,   66,   72,   72,   73,   73,   75,
       75,  149,   72,  430,   73,  149,   75,   76,   76,   79,
       79,  283,   79,   67,   76,  141,   79,  233,   67,  233,
       77,   77,   67,   76,   76,   76,   76,   77,  141,   67,

      429,  141,  283,   67,  428,   67,   77,   77,   77,   77,
       78,   78,  427,  163,  163,   79,  163,   78,  166,  166,
       79,  168,  168,  426,   79,  166,   78,   78,   78,   78,
      425,   79,  174,  174,  424,   79,  423,   79,   87,   87,
       87,   87,   87,   91,   91,   91,   91,   91,  167,  167,
      175,  175,   87,   87,  186,  167,  422,   91,   91,  186,
      421,   87,  170,  170,  420,   87,   87,   87,  419,  170,
       91,   91,   91,   92,  210,  210,   92,  418,   92,   93,
       93,   93,   93,   93,   96,   92,   96,  417,  416,   96,
       96,   96,   96,   96,   92,   98,   98,   98,   98,   98,

      415,  221,   93,  160,  221,  414,   92,  100,  100,  100,
      100,  100,  413,  276,  276,  412,  161,  161,   98,  161,
      160,  160,  160,  160,  172,  172,  162,  162,  411,  162,
      100,  172,  161,  161,  161,  161,  276,  410,  409,  160,
      160,  160,  162,  162,  162,  162,  408,  406,  173,  173,
      282,  161,  161,  161,  164,  173,  282,  176,  176,  177,
      177,  162,  162,  162,  176,  405,  177,  164,  164,  164,
      164,  282,  404,  176,  176,  176,  176,  178,  178,  405,
      403,  402,  179,  179,  178,  401,  164,  164,  164,  179,
      400,  266,  266,  178,  178,  178,  178,  183,  266,  183,

      278,  278,  183,  183,  183,  183,  183,  184,  184,  184,
      184,  184,  189,  399,  189,  267,  267,  189,  189,  189,
      189,  189,  267,  278,  191,  191,  191,  191,  191,  398,
      184,  188,  188,  188,  188,  188,  268,  268,  397,  192,
      192,  396,  395,  268,  394,  188,  188,  191,  193,  193,
      193,  193,  193,  196,  188,  192,  393,  392,  188,  188,
      188,  391,  192,  194,  194,  194,  194,  194,  256,  390,
      389,  196,  196,  192,  388,  387,  386,  194,  196,  381,
      380,  256,  256,  256,  256,  379,  194,  257,  378,  196,
      194,  257,  194,  196,  377,  258,  376,  375,  374,  259,

      256,  256,  256,  260,  257,  257,  257,  257,  258,  258,
      258,  258,  259,  259,  259,  259,  260,  260,  260,  260,
      373,  372,  261,  257,  257,  257,  261,  258,  258,  258,
      371,  259,  259,  259,  262,  260,  260,  260,  269,  269,
      269,  269,  269,  370,  369,  368,  367,  262,  262,  262,
      262,  345,  366,  346,  365,  261,  364,  345,  265,  346,
      261,  363,  265,  362,  261,  263,  262,  262,  262,  264,
      361,  261,  345,  360,  346,  261,  359,  261,  263,  263,
      263,  263,  264,  264,  264,  264,  273,  273,  273,  273,
      273,  265,  358,  357,  356,  355,  265,  263,  263,  263,

      265,  264,  264,  264,  354,  353,  352,  265,  351,  273,
      350,  265,  349,  265,  270,  270,  270,  270,  270,  274,
      274,  274,  274,  274,  334,  333,  332,  330,  270,  329,
      275,  275,  275,  275,  275,  328,  327,  270,  326,  325,
      324,  270,  323,  270,  275,  322,  279,  279,  279,  279,
      279,  321,  284,  275,  320,  319,  318,  275,  317,  275,
      279,  281,  281,  281,  281,  281,  316,  287,  315,  279,
      284,  284,  314,  279,  286,  279,  286,  284,  313,  286,
      286,  286,  286,  286,  281,  287,  287,  312,  284,  310,
      309,  308,  284,  307,  306,  335,  305,  304,  303,  336,

      302,  301,  300,  287,  337,  299,  298,  287,  335,  335,
      335,  335,  336,  336,  336,  336,  297,  337,  337,  337,
      337,  338,  338,  338,  338,  296,  295,  335,  335,  335,
      339,  336,  336,  336,  340,  294,  337,  337,  337,  293,
      338,  338,  338,  339,  339,  339,  339,  340,  340,  340,
      340,  341,  341,  341,  341,  341,  342,  342,  342,  342,
      342,  292,  339,  339,  339,  341,  340,  340,  340,  343,
      343,  343,  343,  343,  341,  291,  290,  289,  341,  342,
      341,  254,  253,  343,  344,  344,  344,  344,  344,  252,
      251,  250,  343,  249,  248,  247,  343,  246,  343,  347,

      347,  347,  347,  347,  245,  244,  243,  344,  348,  348,
      348,  348,  348,  382,  242,  241,  240,  239,  238,  237,
      236,  235,  348,  234,  232,  231,  382,  382,  382,  382,
      230,  348,  229,  228,  227,  348,  226,  348,  383,  383,
      383,  383,  383,  225,  224,  382,  382,  382,  223,  222,
      220,  219,  383,  385,  385,  385,  385,  385,  407,  218,
      217,  383,  216,  215,  214,  383,  213,  383,  212,  211,
      209,  407,  407,  407,  407,  208,  385,  207,  206,  205,
      204,  203,  202,  201,  200,  185,  159,  155,  154,  153,
      407,  407,  407,  439,  439,  439,  439,  439,  439,  439,

      439,  440,  151,  440,  440,  440,  441,  441,  441,  441,
      441,  441,  441,  441,  442,  442,  150,  442,  442,  442,
      442,  442,  443,  443,  443,  443,  443,  443,  443,  443,
      444,  444,  444,  444,  444,  444,  444,  444,  445,  445,
      445,  445,  445,  445,  445,  445,  446,  446,  446,  446,
      446,  446,  446,  446,  447,  447,  447,  447,  447,  447,
      447,  447,  448,  147,  448,  448,  448,  448,  448,  448,
      449,  449,  450,  450,  450,  450,  450,  450,  450,  450,
      451,  146,  451,  451,  451,  451,  451,  451,  452,  452,
      452,  452,  452,  452,  452,  452,  453,  453,  453,  453,

      453,  453,  453,  453,  455,  455,  455,  455,  456,  145,
      456,  143,  142,  140,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  128,  126,  125,  124,  123,  122,  120,
      119,  118,  117,  116,  115,  114,  112,  111,  110,  109,
      108,  102,   97,   88,   86,   63,   54,   51,   48,   46,
       44,   43,   41,   33,   27,   24,   16,   11,    8,    7,
        3,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 3 "lexer.l"
        #include<iostream>
        #include<string>
        #include<utility>
        #include <fstream>
        #include <vector>
        #include <algorithm>
        #include <unordered_map>
        #include "parser.tab.h++"
        using namespace std;
        #include "ast.h"
        #include "parser.hpp"

        void count(void);
        int line = 1;

        unordered_map<string,yytokentype>m(
                {
                        {"abstract",ABSTRACT},
                        {"continue",CONTINUE},
                        {"for",FOR},
                        {"new",NEW},
                        {"switch",SWITCH},
                        {"assert",ASSERT},
                        {"default",DEFAULT},
                        {"if",IF},
                        {"package",PACKAGE},
                        {"synchronized",SYNCHRONIZED},
                        {"boolean",BOOLEAN},
                        {"do",DO},{"goto",GOTO},
                        {"private",PRIVATE},
                        {"this",THIS},
                        {"break",BREAK},
                        {"double",DOUBLE},
                        {"implements",IMPLEMENTS},
                        {"protected",PROTECTED},
                        {"throw",THROW},
                        {"byte",BYTE},
                        {"else",ELSE},
                        {"import",IMPORT},
                        {"public",PUBLIC},
                        {"throws",THROWS},
                        {"case",CASE},
                        {"enum",ENUM},
                        {"instanceof",INSTANCEOF},
                        {"return",RETURN},
                        {"transient",TRANSIENT},
                        {"catch",CATCH},
                        {"extends",EXTENDS},
                        {"int",INT},
                        {"short",SHORT},
                        {"try",TRY},
                        {"char",CHAR},
                        {"final",FINAL},
                        {"interface",INTERFACE},
                        {"static",STATIC},
                        {"void",VOID},
                        {"class",CLASS},
                        {"finally",FINALLY},
                        {"long",LONG},
                        {"strictfp",STRICTFP},
                        {"volatile",VOLATILE},
                        {"const",CONST},
                        {"float",FLOAT},
                        {"native",NATIVE},
                        {"super",SUPER},
                        {"while",WHILE},
                        {"_",UNDERSCORE},
                        {"exports",EXPORTS},
                        {"opens",OPENS},
                        {"requires",REQUIRES},
                        {"uses",USES},
                        {"module",MODULE},
                        {"permits",PERMITS},
                        {"sealed",SEALED},
                        {"var",VAR},
                        {"non-sealed",NON_SEALED},
                        {"provides",PROVIDES},
                        {"to",TO},
                        {"with",WITH},
                        {"open",OPEN},
                        {"record",RECORD},
                        {"transitive",TRANSITIVE},
                        {"yield",YIELD}
                }
        )
        ;
#line 950 "lex.yy.c"
#line 951 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 129 "lexer.l"


#line 1171 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 439 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1162 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 131 "lexer.l"
{count();}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 132 "lexer.l"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 133 "lexer.l"
{}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 134 "lexer.l"
{yylval.str = strdup(yytext); count();return m[string(yytext)]}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 135 "lexer.l"
{yylval.str = strdup(yytext); count(); return integerLiteral;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 136 "lexer.l"
{yylval.str = strdup(yytext); count(); return stringLiteral;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 137 "lexer.l"
{yylval.str = strdup(yytext); count(); return booleanLiteral;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 138 "lexer.l"
{yylval.str = strdup(yytext); count(); return FloatingPointLiteral;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 139 "lexer.l"
{yylval.str = strdup(yytext); count(); return nullLiteral;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 140 "lexer.l"
{yylval.str = strdup(yytext); count(); return characterLiteral;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 141 "lexer.l"
{yylval.str = strdup(yytext); count(); return textBlock;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 142 "lexer.l"
{yylval.str = strdup(yytext); count(); return Identifier;}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 143 "lexer.l"
{yylval.str = strdup(yytext); count(); return compileError;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 144 "lexer.l"
{yylval.str = strdup(yytext); count(); return(UNSIGNED_RIGHT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 145 "lexer.l"
{yylval.str = strdup(yytext); count(); return(UNSIGNED_RIGHT_ASSIGN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 146 "lexer.l"
{yylval.str = strdup(yytext); count(); return(METHOD_REFERENCE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 147 "lexer.l"
{yylval.str = strdup(yytext); count(); return(ELLIPSIS); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 148 "lexer.l"
{yylval.str = strdup(yytext); count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 149 "lexer.l"
{yylval.str = strdup(yytext); count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 150 "lexer.l"
{yylval.str = strdup(yytext); count(); return(ADD_ASSIGN); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 151 "lexer.l"
{yylval.str = strdup(yytext); count(); return(SUB_ASSIGN); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 152 "lexer.l"
{yylval.str = strdup(yytext); count(); return(MUL_ASSIGN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 153 "lexer.l"
{yylval.str = strdup(yytext); count(); return(DIV_ASSIGN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 154 "lexer.l"
{yylval.str = strdup(yytext); count(); return(MOD_ASSIGN); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 155 "lexer.l"
{yylval.str = strdup(yytext); count(); return(AND_ASSIGN); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 156 "lexer.l"
{yylval.str = strdup(yytext); count(); return(XOR_ASSIGN); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 157 "lexer.l"
{yylval.str = strdup(yytext); count(); return(OR_ASSIGN); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 158 "lexer.l"
{yylval.str = strdup(yytext); count(); return(RIGHT_OP); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 159 "lexer.l"
{yylval.str = strdup(yytext); count(); return(LEFT_OP); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 160 "lexer.l"
{yylval.str = strdup(yytext); count(); return(INC_OP); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 161 "lexer.l"
{yylval.str = strdup(yytext); count(); return(DEC_OP); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 162 "lexer.l"
{yylval.str = strdup(yytext); count(); return(PTR_OP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 163 "lexer.l"
{yylval.str = strdup(yytext); count(); return(AND_OP); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 164 "lexer.l"
{yylval.str = strdup(yytext); count(); return(OR_OP); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 165 "lexer.l"
{yylval.str = strdup(yytext); count(); return(LE_OP); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 166 "lexer.l"
{yylval.str = strdup(yytext); count(); return(GE_OP); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 167 "lexer.l"
{yylval.str = strdup(yytext); count(); return(EQ_OP); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 168 "lexer.l"
{yylval.str = strdup(yytext); count(); return(NE_OP); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 169 "lexer.l"
{yylval.str = strdup(yytext); count(); return(';'); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 170 "lexer.l"
{yylval.str = strdup(yytext); count(); return('@'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 171 "lexer.l"
{yylval.str = strdup(yytext); count(); return('{'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 172 "lexer.l"
{yylval.str = strdup(yytext); count(); return('}'); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 173 "lexer.l"
{yylval.str = strdup(yytext); count(); return(','); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 174 "lexer.l"
{yylval.str = strdup(yytext); count(); return(':'); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 175 "lexer.l"
{yylval.str = strdup(yytext); count(); return('='); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 176 "lexer.l"
{yylval.str = strdup(yytext); count(); return('('); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 177 "lexer.l"
{yylval.str = strdup(yytext); count(); return(')'); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 178 "lexer.l"
{yylval.str = strdup(yytext); count(); return('['); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 179 "lexer.l"
{yylval.str = strdup(yytext); count(); return(']'); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 180 "lexer.l"
{yylval.str = strdup(yytext); count(); return('.'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 181 "lexer.l"
{yylval.str = strdup(yytext); count(); return('&'); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 182 "lexer.l"
{yylval.str = strdup(yytext); count(); return('!'); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 183 "lexer.l"
{yylval.str = strdup(yytext); count(); return('~'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 184 "lexer.l"
{yylval.str = strdup(yytext); count(); return('-'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 185 "lexer.l"
{yylval.str = strdup(yytext); count(); return('+'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 186 "lexer.l"
{yylval.str = strdup(yytext); count(); return('*'); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 187 "lexer.l"
{yylval.str = strdup(yytext); count(); return('/'); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 188 "lexer.l"
{yylval.str = strdup(yytext); count(); return('%'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 189 "lexer.l"
{yylval.str = strdup(yytext); count(); return('<'); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 190 "lexer.l"
{yylval.str = strdup(yytext); count(); return('>'); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 191 "lexer.l"
{yylval.str = strdup(yytext); count(); return('^'); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 192 "lexer.l"
{yylval.str = strdup(yytext); count(); return('|'); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 193 "lexer.l"
{yylval.str = strdup(yytext); count(); return('?'); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 194 "lexer.l"
{yylval.str =  "<EOF>"; return EOF;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 195 "lexer.l"
{
        cout<<"illegal character on line "<<line<<" :"<<yytext<<endl;
        return -1;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 200 "lexer.l"
ECHO;
	YY_BREAK
#line 1565 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 439 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 439 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 438);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 200 "lexer.l"


int yywrap()
{
      return(1);
}

void count(void)
{
      for (i = 0; yytext[i] != '\0'; i++) 
        if (yytext[i] == '\n') line ++;
      return;  
}

