
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[395] =
    {   0,
        0,    0,   62,   60,    2,    1,    1,   48,   60,   12,
       54,   47,   60,   42,   43,   52,   51,   39,   50,   46,
       53,    5,    5,   40,   35,   55,   41,   56,   59,   36,
       44,   45,   57,    4,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   37,   58,   38,   49,    1,   34,
        0,    6,    0,    0,    0,    0,   12,   21,   29,   22,
        0,    0,    0,    0,    0,   19,   27,   17,   28,   18,
        8,    0,    0,   20,    8,    5,    0,    0,    8,    0,
        0,    0,    5,    0,   26,   31,   33,   32,   25,   23,

       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        4,   12,   12,   12,   12,   12,   12,   12,   12,    4,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   24,   30,    6,    0,
        0,    0,   10,   10,    0,    0,    0,    8,    8,    0,
        0,    0,    0,    3,    8,    0,    5,    0,    5,    0,
        8,    0,    5,    5,   16,   15,   13,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,    4,

       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,    0,
        0,    0,    0,    0,    0,    0,    8,    3,    8,    0,
        0,    8,    5,    5,    0,    8,    8,    0,    0,    0,
        5,    5,    0,    0,   14,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,    0,    9,    4,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,    7,   12,   12,   12,    0,

        0,    0,    0,    8,    0,    8,    0,    0,    0,    0,
        8,   12,   12,   12,   12,   12,   12,   12,   12,    4,
       12,   12,   12,   12,   12,   12,    0,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        4,   12,   12,    0,    8,    8,    0,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    0,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   11,   12,   12,
       12,   12,   12,    0,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,    0,   12,   12,   12,   12,   12,
        0,   12,    4,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   31,   33,   34,   33,
        7,    7,    7,    7,    7,   35,    7,    7,    7,   36,
        7,    7,    7,    7,    7,    7,    7,   37,    7,    7,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,    7,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,    7,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    1,
        6,    6,    6,    6,    7,    8,    3,    1,    1,    1,
        1,    8,    6,    6,    6,    6,    6,    6,    3,    3,
        3,    3,    7,    3,    3,    3,    8,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[405] =
    {   0,
        0,    0,  932,  933,  933,  933,  928,  903,   65,    0,
      902,   63,   54,  933,  933,  901,   64,  933,   61,   60,
       82,   93,  142,  933,  933,   70,  900,   71,  933,  933,
      933,  933,  899,    0,   57,   52,   78,   73,   83,   99,
      869,   99,  868,  867,  123,  865,  124,  874,   96,  118,
      860,   46,   56,  868,  933,  105,  933,  933,  933,  933,
      172,  912,  176,  181,  203,  207,    0,  933,  933,  933,
      907,  208,  216,  237,  234,  933,  933,  933,  933,  933,
      277,  903,    0,  933,  282,  299,  264,  103,  933,  319,
      898,  325,   98,  334,  887,  933,  933,  933,  117,  933,

      853,  852,  855,  863,  848,  120,  865,  864,  851,  857,
      842,  843,  840,  147,  848,  845,  843,  839,  836,    0,
      839,  145,  840,  848,  832,  828,  836,  837,  842,  843,
      828,   68,  842,  111,  842,  828,  189,  832,  148,  188,
      835,  822,  210,  829,  818,  831,  933,  933,  933,  349,
      353,  359,  933,  933,  250,  867,  255,    0,  933,  386,
      391,  863,  221,    0,  415,  401,  933,  408,  342,  420,
      432,    0,  441,  933,  933,  933,  848,  812,  804,  784,
      792,  783,  782,  776,  757,  755,  192,  771,  769,  765,
      757,  754,  762,  748,  764,  763,  749,  211,  743,  755,

      748,  734,  744,  777,  738,  735,  737,  733,  723,  218,
      725,  721,  714,  713,  718,  711,  702,  710,  699,  699,
      701,  697,  704,  690,  702,  704,  693,  695,  691,  450,
      480,  485,  489,  511,  516,  493,  515,  933,    0,  520,
      546,  559,  271,  933,  307,  564,  933,  594,  252,  301,
      585,  933,  609,  537,  933,  684,  683,  694,  681,  682,
      671,  663,  671,  659,  667,  659,  662,  669,  653,  644,
      657,  643,  658,  636,  640,  629,  631,    0,  630,  633,
      621,  625,  617,  612,  611,  586,  593,  584,  593,  578,
      584,  589,  581,  560,  562,    0,  558,  571,  565,  627,

      631,  635,  639,  661,  666,  677,  692,  390,  424,  707,
      716,  566,  547,  561,  548,  547,  552,  537,  550,  542,
      539,  530,  534,  540,  529,  527,  523,  510,  497,  495,
      508,  506,  502,  500,  486,  489,  475,  458,  436,  446,
      433,  441,  436,  734,  746,  933,  761,  440,  429,  417,
      414,  413,  408,  401,  417,  414,  403,  402,  397,  365,
      372,  357,  369,  357,  355,  260,  348,  779,  335,  347,
      335,  339,  340,  330,  335,  306,  303,  303,  295,  281,
      275,  259,  262,  270,  267,  266,  247,  229,  220,  201,
      199,  186,  933,  933,  819,  825,  833,  841,  849,  853,

      859,  143,  863,  866
    } ;

static const flex_int16_t yy_def[405] =
    {   0,
      394,    1,  394,  394,  394,  394,  394,  394,  395,  396,
      394,  394,  397,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  394,  394,  394,  394,  394,  394,
      395,  394,  395,  395,  395,  394,  396,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  398,  399,  394,  394,   22,   23,  394,  394,  394,
      400,  394,   23,  394,  394,  394,  394,  394,  394,  394,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  394,  394,  394,  401,
      395,  395,  394,  394,  394,  394,  394,   81,  394,  394,
      394,  398,  398,  399,  394,  394,  394,  394,  394,  394,
      394,  402,  403,  394,  394,  394,  394,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  401,
      401,  401,  401,  401,  394,  394,  394,  394,  165,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  404,  402,
      403,  394,  394,  251,  394,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  394,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  401,

      401,  401,  401,  394,  394,  394,  394,  404,  404,  394,
      394,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  394,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  401,  394,  394,  394,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  394,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  401,  396,  396,
      396,  396,  396,  394,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  394,  396,  396,  396,  396,  396,
      394,  396,  394,    0,  394,  394,  394,  394,  394,  394,

      394,  394,  394,  394
    } ;

static const flex_int16_t yy_nxt[1004] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   24,   25,   26,   27,   28,   29,   30,
       10,   10,   10,   10,   10,   10,   10,   31,    4,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   10,
       42,   10,   43,   44,   45,   46,   47,   10,   48,   49,
       50,   51,   52,   53,   10,   54,   55,   56,   57,   58,
       62,   69,   72,   72,   72,   73,   79,   77,   81,   81,
       81,   81,   81,   63,   63,   63,   64,   80,  142,   70,
       78,   74,   75,   74,   82,   95,   96,   98,   99,   83,

      101,  143,   65,   66,   65,  144,  145,  103,   84,   85,
      104,   86,   86,   86,   86,   87,  102,  105,  209,  110,
      106,  169,  169,  210,   88,   89,   90,  107,  111,   91,
      108,  147,  174,  109,   92,  112,   88,  113,   89,   90,
       89,  115,  135,  176,  177,  136,  120,  114,  249,  116,
      174,  117,  121,  122,  118,  212,  137,   91,   85,  138,
       93,   93,   93,   93,   93,  125,  130,  139,  213,  126,
      131,  214,  148,  120,   89,   90,  140,  149,  127,  183,
      184,  149,  132,   94,  128,  133,  149,   89,   90,   89,
       63,   63,   63,   64,  151,  151,  151,  152,  220,  151,

      151,  151,  152,  192,  199,  200,  221,  193,  149,   65,
       66,   65,   61,   65,   66,   65,   61,  154,   65,   66,
       65,   63,   63,   63,   64,  154,  155,  155,  155,  155,
      222,  217,  120,  163,  156,  156,  156,  156,  238,  156,
       65,   66,   65,  156,  393,   61,  153,  218,  120,  223,
       61,  262,  263,  120,   61,  157,  157,  157,  157,  153,
      225,   61,  226,  271,  153,   61,  272,   61,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  283,  120,
      284,  156,   87,   87,   87,   87,   87,  253,  156,  243,
      243,  392,  156,  309,  156,  158,  158,  158,  158,  158,

      165,  165,  165,  165,  165,  168,  379,  120,  253,  159,
      160,  120,  245,  391,   89,  166,  120,  390,  161,  389,
      380,  120,  159,  160,  159,  243,  243,   89,  166,   89,
      394,  388,  170,  167,  170,  394,  253,  171,  171,  171,
      171,  171,  394,   86,   86,   86,   86,   87,  245,  387,
      231,  167,   93,   93,   93,   93,   93,  253,  149,  120,
      243,  243,  120,  394,  149,  120,   92,  232,  232,  232,
      233,  151,  151,  151,  152,   94,  244,  151,  151,  151,
      152,  386,  385,  245,  384,  383,  234,  235,  234,  382,
       65,   66,   65,  120,  244,  120,   65,   66,   65,  236,

      381,  236,  378,  377,  237,  237,  237,  237,  237,  158,
      158,  158,  158,  158,  241,  376,  241,  375,  120,  242,
      242,  242,  242,  242,  120,  253,   87,   87,   87,   87,
       87,  309,  161,  239,  239,  239,  239,  239,  171,  171,
      171,  171,  171,  120,  374,  373,  253,   89,  166,  168,
      246,  246,  246,  246,  246,  300,  240,  250,  372,  394,
       89,  166,   89,  371,  247,  309,  120,  120,  232,  232,
      232,  233,  120,  248,  120,  252,  253,  247,  370,  247,
      394,  231,  254,  120,  369,  300,  367,  234,  235,  234,
      300,  366,  120,  252,  300,  120,  365,  253,  232,  232,

      232,  233,  120,  301,  301,  301,  302,  301,  301,  301,
      302,  237,  237,  237,  237,  237,  300,  234,  235,  234,
      120,  303,  234,  235,  234,  303,  234,  235,  234,  232,
      232,  232,  233,  304,  304,  304,  304,  304,  239,  239,
      239,  239,  239,  120,  364,  120,  120,  159,  234,  235,
      234,  363,  362,  394,  303,  361,  305,  360,  359,  303,
      159,  240,  159,  303,  242,  242,  242,  242,  242,  358,
      303,  394,  394,  120,  303,  120,  303,  306,  306,  306,
      306,  306,  246,  246,  246,  246,  246,  357,  356,  394,
      120,   89,  355,  394,  354,  353,  247,  352,  120,  351,

      307,  250,  350,  349,   89,  248,   89,  120,  348,  247,
      120,  247,  246,  246,  246,  246,  246,  120,  343,  252,
      253,  342,  310,  341,  310,  340,  254,  311,  311,  311,
      311,  311,  344,  339,  338,  248,  300,  252,  120,  337,
      300,  253,  336,  335,  334,  232,  232,  232,  233,  301,
      301,  301,  302,  301,  301,  301,  302,  232,  232,  232,
      233,  333,  332,  331,  234,  235,  234,  330,  234,  235,
      234,  329,  234,  235,  234,  328,  234,  235,  234,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  120,
      327,  326,  325,  159,  324,  306,  306,  306,  306,  306,

      323,  322,  305,  321,  120,  320,  159,  305,  159,   89,
      306,  306,  306,  306,  306,  296,  319,  318,  307,  317,
      316,  315,   89,  120,   89,  311,  311,  311,  311,  311,
      120,  120,  120,  307,  345,  345,  345,  345,  345,  368,
      314,  313,  312,  299,  120,  298,  297,  120,  346,  120,
      296,  295,  232,  232,  232,  233,  294,  347,  120,  293,
      292,  346,  291,  346,  345,  345,  345,  345,  345,  290,
      289,  234,  235,  234,  288,  287,  286,  285,  346,  345,
      345,  345,  345,  345,  368,  282,  281,  347,  280,  279,
      278,  346,  277,  346,  276,  275,  120,  232,  232,  232,

      233,  274,  347,  273,  120,  270,  269,  268,  267,  266,
      120,  120,  265,  264,  261,  120,  234,  235,  234,   61,
      260,   61,   61,   61,   61,   61,   61,   67,  120,  120,
       67,   67,   67,   71,  259,   71,  258,   71,   71,   71,
       71,  162,  162,  162,  162,  162,  162,  162,  162,  164,
      257,  164,  164,  164,  164,  164,  164,  173,  173,  230,
      230,  230,  230,  230,  230,  230,  230,  251,  251,  251,
      251,  308,  256,  308,  255,  163,  153,  229,  228,  227,
      120,  224,  219,  216,  215,  211,  208,  207,  206,  205,
      204,  120,  203,  202,  201,  198,  197,  120,  196,  195,

      194,  191,  190,  189,  188,  187,  186,  185,  182,  181,
      180,  179,  178,  175,  172,  163,  153,  150,  146,  141,
      134,  129,  124,  123,  119,  100,   97,   76,   68,   60,
       59,  394,    3,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,

      394,  394,  394
    } ;

static const flex_int16_t yy_chk[1004] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        9,   12,   13,   13,   13,   13,   19,   17,   20,   20,
       20,   20,   20,    9,    9,    9,    9,   19,   52,   12,
       17,   13,   13,   13,   21,   26,   26,   28,   28,   21,

       35,   52,    9,    9,    9,   53,   53,   36,   21,   22,
       36,   22,   22,   22,   22,   22,   35,   36,  132,   38,
       37,   88,   88,  132,   22,   22,   22,   37,   38,   22,
       37,   56,   93,   37,   22,   39,   22,   39,   22,   22,
       22,   40,   49,   99,   99,   49,   42,   39,  402,   40,
       93,   40,   42,   42,   40,  134,   49,   22,   23,   49,
       23,   23,   23,   23,   23,   45,   47,   50,  134,   45,
       47,  134,   56,   50,   23,   23,   50,   61,   45,  106,
      106,   63,   47,   23,   45,   47,   64,   23,   23,   23,
       61,   61,   61,   61,   63,   63,   63,   63,  139,   64,

       64,   64,   64,  114,  122,  122,  139,  114,   65,   61,
       61,   61,   66,   63,   63,   63,   66,   72,   64,   64,
       64,   65,   65,   65,   65,   73,   72,   72,   72,   72,
      140,  137,  392,  163,   73,   73,   73,   73,  163,   75,
       65,   65,   65,   75,  391,   66,   74,  137,  390,  140,
       66,  187,  187,  140,   66,   74,   74,   74,   74,  155,
      143,   66,  143,  198,  157,   66,  198,   66,  155,  155,
      155,  155,   75,  157,  157,  157,  157,   75,  210,  389,
      210,   75,   87,   87,   87,   87,   87,  249,   75,  243,
      243,  388,   75,  249,   75,   81,   81,   81,   81,   81,

       85,   85,   85,   85,   85,   87,  366,  387,  249,   81,
       81,  386,  243,  385,   85,   85,  384,  383,   81,  382,
      366,  381,   81,   81,   81,  245,  245,   85,   85,   85,
       86,  380,   90,   86,   90,   86,  250,   90,   90,   90,
       90,   90,   86,   92,   92,   92,   92,   92,  245,  379,
      150,   86,   94,   94,   94,   94,   94,  250,  151,  378,
      169,  169,  377,   86,  152,  376,   92,  150,  150,  150,
      150,  151,  151,  151,  151,   94,  169,  152,  152,  152,
      152,  375,  374,  169,  373,  372,  150,  150,  150,  371,
      151,  151,  151,  370,  169,  369,  152,  152,  152,  160,

      367,  160,  365,  364,  160,  160,  160,  160,  160,  161,
      161,  161,  161,  161,  166,  363,  166,  362,  361,  166,
      166,  166,  166,  166,  360,  308,  168,  168,  168,  168,
      168,  308,  161,  165,  165,  165,  165,  165,  170,  170,
      170,  170,  170,  359,  358,  357,  308,  165,  165,  168,
      171,  171,  171,  171,  171,  230,  165,  173,  356,  309,
      165,  165,  165,  355,  171,  309,  354,  353,  230,  230,
      230,  230,  352,  171,  351,  173,  173,  171,  350,  171,
      309,  231,  173,  349,  348,  231,  343,  230,  230,  230,
      232,  342,  341,  173,  233,  340,  339,  173,  231,  231,

      231,  231,  338,  232,  232,  232,  232,  233,  233,  233,
      233,  236,  236,  236,  236,  236,  234,  231,  231,  231,
      337,  235,  232,  232,  232,  235,  233,  233,  233,  234,
      234,  234,  234,  237,  237,  237,  237,  237,  240,  240,
      240,  240,  240,  336,  335,  334,  333,  237,  234,  234,
      234,  332,  331,  254,  235,  330,  237,  329,  328,  235,
      237,  240,  237,  235,  241,  241,  241,  241,  241,  327,
      235,  254,  254,  326,  235,  325,  235,  242,  242,  242,
      242,  242,  246,  246,  246,  246,  246,  324,  323,  254,
      322,  242,  321,  254,  320,  319,  246,  318,  317,  316,

      242,  251,  315,  314,  242,  246,  242,  313,  312,  246,
      299,  246,  248,  248,  248,  248,  248,  298,  297,  251,
      251,  295,  253,  294,  253,  293,  251,  253,  253,  253,
      253,  253,  300,  292,  291,  248,  301,  251,  290,  289,
      302,  251,  288,  287,  286,  300,  300,  300,  300,  301,
      301,  301,  301,  302,  302,  302,  302,  303,  303,  303,
      303,  285,  284,  283,  300,  300,  300,  282,  301,  301,
      301,  281,  302,  302,  302,  280,  303,  303,  303,  304,
      304,  304,  304,  304,  305,  305,  305,  305,  305,  279,
      277,  276,  275,  304,  274,  306,  306,  306,  306,  306,

      273,  272,  304,  271,  270,  269,  304,  305,  304,  306,
      307,  307,  307,  307,  307,  268,  267,  266,  306,  265,
      264,  263,  306,  262,  306,  310,  310,  310,  310,  310,
      261,  260,  259,  307,  311,  311,  311,  311,  311,  344,
      258,  257,  256,  229,  228,  227,  226,  225,  311,  224,
      223,  222,  344,  344,  344,  344,  221,  311,  220,  219,
      218,  311,  217,  311,  345,  345,  345,  345,  345,  216,
      215,  344,  344,  344,  214,  213,  212,  211,  345,  347,
      347,  347,  347,  347,  368,  209,  208,  345,  207,  206,
      205,  345,  204,  345,  203,  202,  201,  368,  368,  368,

      368,  200,  347,  199,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  186,  185,  368,  368,  368,  395,
      184,  395,  395,  395,  395,  395,  395,  396,  183,  182,
      396,  396,  396,  397,  181,  397,  180,  397,  397,  397,
      397,  398,  398,  398,  398,  398,  398,  398,  398,  399,
      179,  399,  399,  399,  399,  399,  399,  400,  400,  401,
      401,  401,  401,  401,  401,  401,  401,  403,  403,  403,
      403,  404,  178,  404,  177,  162,  156,  146,  145,  144,
      142,  141,  138,  136,  135,  133,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  121,  119,  118,  117,  116,

      115,  113,  112,  111,  110,  109,  108,  107,  105,  104,
      103,  102,  101,   95,   91,   82,   71,   62,   54,   51,
       48,   46,   44,   43,   41,   33,   27,   16,   11,    8,
        7,    3,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,

      394,  394,  394
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
        #include<iostream>
        #include<cstring>
        #include<utility>
        #include <fstream>
        #include <vector>
        #include <algorithm>
        #include <unordered_map>
        using namespace std;
        #include "ast.h"
        #include "parser.hpp"
        void count(void);
        int line = 1;
        void yyerror(char const*);        

        unordered_map<string,yytokentype>m(
                {
                        {"continue",CONTINUE},
                        {"for",FOR},
                        {"new",NEW},
                        {"if",IF},
                        {"package",PACKAGE},
                        {"boolean",BOOLEAN},
                        {"private",PRIVATE},
                        {"this",THIS},
                        {"break",BREAK},
                        {"double",DOUBLE},
                        {"throw",THROW},
                        {"byte",BYTE},
                        {"else",ELSE},
                        {"public",PUBLIC},
                        {"return",RETURN},
                        {"int",INT},
                        {"short",SHORT},
                        {"char",CHAR},
                        {"final",FINAL},
                        {"static",STATIC},
                        {"void",VOID},
                        {"class",CLASS},
                        {"long",LONG},
                        {"float",FLOAT},
                        {"while",WHILE},
                        {"yield",YIELD}
                }
        )
        ;
#line 844 "lex.yy.c"
#line 845 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 83 "lexer.l"


#line 1065 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 395 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 933 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 85 "lexer.l"
{count();}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 86 "lexer.l"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 87 "lexer.l"
{count();}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 88 "lexer.l"
{yylval.str = strdup(yytext); count(); return m[string(yytext)];}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 89 "lexer.l"
{yylval.str = strdup(yytext); count(); return integerLiteral;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 90 "lexer.l"
{yylval.str = strdup(yytext); count(); return stringLiteral;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "lexer.l"
{yylval.str = strdup(yytext); count(); return booleanLiteral;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "lexer.l"
{yylval.str = strdup(yytext); count(); return FloatingPointLiteral;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "lexer.l"
{yylval.str = strdup(yytext); count(); return nullLiteral;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "lexer.l"
{yylval.str = strdup(yytext); count(); return characterLiteral;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 95 "lexer.l"
{yylval.str = strdup(yytext); count(); return textBlock;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 96 "lexer.l"
{yylval.str = strdup(yytext); count(); return Identifier;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 97 "lexer.l"
{yylval.str = strdup(yytext); count(); return(UNSIGNED_RIGHT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 98 "lexer.l"
{yylval.str = strdup(yytext); count(); return(UNSIGNED_RIGHT_ASSIGN); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 99 "lexer.l"
{yylval.str = strdup(yytext); count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 100 "lexer.l"
{yylval.str = strdup(yytext); count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 101 "lexer.l"
{yylval.str = strdup(yytext); count(); return(ADD_ASSIGN); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 102 "lexer.l"
{yylval.str = strdup(yytext); count(); return(SUB_ASSIGN); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 103 "lexer.l"
{yylval.str = strdup(yytext); count(); return(MUL_ASSIGN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 104 "lexer.l"
{yylval.str = strdup(yytext); count(); return(DIV_ASSIGN); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 105 "lexer.l"
{yylval.str = strdup(yytext); count(); return(MOD_ASSIGN); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 106 "lexer.l"
{yylval.str = strdup(yytext); count(); return(AND_ASSIGN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 107 "lexer.l"
{yylval.str = strdup(yytext); count(); return(XOR_ASSIGN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 108 "lexer.l"
{yylval.str = strdup(yytext); count(); return(OR_ASSIGN); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 109 "lexer.l"
{yylval.str = strdup(yytext); count(); return(RIGHT_OP); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 110 "lexer.l"
{yylval.str = strdup(yytext); count(); return(LEFT_OP); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 111 "lexer.l"
{yylval.str = strdup(yytext); count(); return(INC_OP); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 112 "lexer.l"
{yylval.str = strdup(yytext); count(); return(DEC_OP); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 113 "lexer.l"
{yylval.str = strdup(yytext); count(); return(AND_OP); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 114 "lexer.l"
{yylval.str = strdup(yytext); count(); return(OR_OP); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 115 "lexer.l"
{yylval.str = strdup(yytext); count(); return(LE_OP); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 116 "lexer.l"
{yylval.str = strdup(yytext); count(); return(GE_OP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 117 "lexer.l"
{yylval.str = strdup(yytext); count(); return(EQ_OP); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 118 "lexer.l"
{yylval.str = strdup(yytext); count(); return(NE_OP); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 119 "lexer.l"
{yylval.str = strdup(yytext); count(); return(';'); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 120 "lexer.l"
{yylval.str = strdup(yytext); count(); return('@'); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 121 "lexer.l"
{yylval.str = strdup(yytext); count(); return('{'); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 122 "lexer.l"
{yylval.str = strdup(yytext); count(); return('}'); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 123 "lexer.l"
{yylval.str = strdup(yytext); count(); return(','); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 124 "lexer.l"
{yylval.str = strdup(yytext); count(); return(':'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 125 "lexer.l"
{yylval.str = strdup(yytext); count(); return('='); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 126 "lexer.l"
{yylval.str = strdup(yytext); count(); return('('); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 127 "lexer.l"
{yylval.str = strdup(yytext); count(); return(')'); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 128 "lexer.l"
{yylval.str = strdup(yytext); count(); return('['); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 129 "lexer.l"
{yylval.str = strdup(yytext); count(); return(']'); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 130 "lexer.l"
{yylval.str = strdup(yytext); count(); return('.'); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 131 "lexer.l"
{yylval.str = strdup(yytext); count(); return('&'); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 132 "lexer.l"
{yylval.str = strdup(yytext); count(); return('!'); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 133 "lexer.l"
{yylval.str = strdup(yytext); count(); return('~'); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 134 "lexer.l"
{yylval.str = strdup(yytext); count(); return('-'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 135 "lexer.l"
{yylval.str = strdup(yytext); count(); return('+'); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 136 "lexer.l"
{yylval.str = strdup(yytext); count(); return('*'); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 137 "lexer.l"
{yylval.str = strdup(yytext); count(); return('/'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 138 "lexer.l"
{yylval.str = strdup(yytext); count(); return('%'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 139 "lexer.l"
{yylval.str = strdup(yytext); count(); return('<'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 140 "lexer.l"
{yylval.str = strdup(yytext); count(); return('>'); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 141 "lexer.l"
{yylval.str = strdup(yytext); count(); return('^'); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 142 "lexer.l"
{yylval.str = strdup(yytext); count(); return('|'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 143 "lexer.l"
{yylval.str = strdup(yytext); count(); return('?'); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 144 "lexer.l"
{
        cout<<"illegal character on line "<<line<<" :"<<yytext<<endl;
        return -1;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 149 "lexer.l"
ECHO;
	YY_BREAK
#line 1434 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 395 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 395 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 394);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 149 "lexer.l"


int yywrap()
{
      return(1);
}



void count(void)
{
      for (int i = 0; yytext[i] != '\0'; i++) 
        if (yytext[i] == '\n') line ++;
      return;  
}




